server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/entitiesdb
    username: pguser
    password: pgpass
#  flyway.enabled: true
#  flyway:
#    locations: classpath:db.migrations
#    schemas: file
#    url: jdbc:postgresql://localhost:5432/countbytesdb
#    user: pguser
#    password: pgpass
#    baselineOnMigrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true

keycloak:
  realm: spring-example
  resource: entity-manipulation-client
  auth-server-url: http://localhost:8080
  credentials:
    secret: W1ZuDtIY5AkAEFkCvKLApgYTX7HGLQrB
#  use-resource-role-mappings: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG