server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/entitiesdb
    username: pguser
    password: pgpass
#  flyway.enabled: true
#  flyway:
#    locations: classpath:db.migrations
#    schemas: file
#    url: jdbc:postgresql://localhost:5432/countbytesdb
#    user: pguser
#    password: pgpass
#    baselineOnMigrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core: DEBUG